services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: bird-detection-backend
    environment:
      PORT: 5000
    expose:
      - "5000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: bird-detection-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
